version: '3.8'

services:
  productgatewayapi:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_DBNAME=postgres
      - DB_SSLMODE=disable
      - DB_PASSWORD=root
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: